#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2017-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import enum
import re
import sys

def attr2func(f):
    class attr2func:
        def __getattr__(self, name):
            return f(name)
    return attr2func()

def _gen_regexps():
    x = attr2func(lambda name: fr'(?P<{name}>[0-9a-f]+)')
    pid = r'\[\d+\]'
    vma = fr'(?P<elf>\S+)\[{x.vmstart}[+]{x.vmsize}\]'
    yield (
        # show_signal() in <arch/x86/kernel/traps.c>:
        fr'{pid} (?P<type>.*) ip:{x.ip} sp:{x.sp} error:{x.err} in {vma}'
    )
    yield (
        # show_signal_msg() in <arch/x86/mm/fault.c>:
        fr'{pid}: (?P<type>segfault) at {x.at} ip {x.ip} sp {x.sp} error {x.err} in {vma}'
    )

regexps = [re.compile(r) for r in _gen_regexps()]

def fmt_addr(addr):
    if isinstance(addr, str):
        addr = int(addr, 16)
    return f'0x{addr:012X}'

class PFErrorCode(enum.IntFlag):
    # enum x86_pf_error_code in <arch/x86/include/asm/trap_pf.h>:
    X86_PF_PROT  = 1 << 0   # 0 = no page found; 1 = protection fault 
    X86_PF_WRITE = 1 << 1   # 0 = read access; 1 = write access 
    X86_PF_USER  = 1 << 2   # 0 = kernel-mode access; 1 = user-mode access 
    X86_PF_RSVD  = 1 << 3   # use of reserved bit detected 
    X86_PF_INSTR = 1 << 4   # fault was an instruction fetch 
    X86_PF_PK    = 1 << 5   # protection keys block access 
    X86_PF_SGX   = 1 << 15  # SGX MMU page-fault 

    def __str__(self):
        s = super().__str__()
        s = re.sub('^\w+[.]', '', s)
        s = re.sub('[|]', ' | ', s)
        return s

def fmt_err(err):
    if isinstance(err, str):
        err = int(err, 16)
    s = f'0x{err:04X}'
    if err != 0:
        s += f' ({PFErrorCode(err)})'
    return s

def main():
    ap = argparse.ArgumentParser()
    ap.parse_args()
    prog = ap.prog
    for line in sys.stdin:
        for regexp in regexps:
            match = regexp.search(line)
            if match is not None:
                break
        else:
            print(f'{prog}: cannot parse:', line, file=sys.stderr)
        g = attr2func(match.group)
        print('Type:', g.type)
        print('Error:', fmt_err(g.err))
        try:
            at = g.at
        except IndexError:
            pass
        else:
            print('At:', fmt_addr(g.at))
        print('SP:', fmt_addr(g.sp))
        print('IP:', fmt_addr(g.ip))
        print('VMA at:', fmt_addr(g.vmstart))
        print('VMA size:', fmt_addr(g.vmsize))
        print()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
