name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.8'
          os: ubuntu-22.04
        - python: '3.9'
          os: ubuntu-22.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install gcc-multilib  # needed for -m32 support
      run: |
        sudo apt-get install gcc-multilib
    - name: install pyelftools
      run: |
        # TODO: test against old versions
        python3 -m pip install pyelftools
    - name: build tests
      run:
        make -C test
    - name: disable printk rate limiting
      run:
        sudo sysctl kernel.printk_ratelimit=0
    - name: patch out use of dmesg --since
      if: matrix.os == 'ubuntu-20.04'
      run:
        sed -i -e '/--since=/d' test/crash.t
    - name: clear dmesg
      run:
        # not strictly necessary,
        # but it makes debugging easier
        sudo dmesg --clear
    - name: install colorized-logs
      run: |
        sudo apt-get install colorized-logs
    - name: run tests
      run:
        # use pipetty(1) to ensure timely output from "prove -v"
        pipetty make -C test test
      timeout-minutes: 1
    - name: dump dmesg
      run:
        sudo dmesg --time-format=iso
      if: success() || failure()
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
